import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import Image from "next/image";
import Cabecalho from "./cabecalho";
import Link from "next/link";

export default function Home() {
  const [dados, setDados] = useState([]);

  useEffect(() => {
    const fetchDados = async () => {
      try {
        const response = await fetch("/api/dados");
        const data = await response.json();
        console.log("Dados buscados:", data);
        setDados(data);
      } catch (error) {
        console.error("Erro ao buscar dados:", error);
      }
    };

    fetchDados();
  }, []);

  return (
    <>
      <Head>
        <title>BlogProject</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <Cabecalho/>

        <div className={styles.conteudo}>
          {dados.map((item) => (
            <div key={item.id}>
              <Link href={item.link} target="_blank">
              <Image
                className={styles.imagem}
                width={390}
                height={270}
                src={item.imagem}
                alt={item.name}
              />
              </Link>
              <div className={item.container}>
                <h2>{item.nome}</h2>
                <p>{item.descricao}</p>
                <h3>{item.autor}</h3>
                <p>{item.data}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}